module.exports={
     Getdata:"http://localhost:5053/get/getcategory",
      Postdata:"http://localhost:5053/get/addcategory",
      Deletedata:"http://localhost:5053/get/deletecategory/",
      Singledata:"http://localhost:5053/get/getsinglecategory/",
      Updatedata:"http://localhost:5053/get/upadtecategory/",
      GetProductData:"http://localhost:5053/getproduct/getProduct",
      postProductData:"http://localhost:5053/getproduct/addProduct",
      DeleteProductdata:"http://localhost:5053/getproduct/deleteProduct/",
      SingleProductdata:"http://localhost:5053/getproduct/getsingleProduct/",
      UpdateProductdata:"http://localhost:5053/getproduct/upadteProduct/"
}